sudo: false
language: node_js
node_js:
  - 8
  - 7
os:
  - linux
  - osx
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
cache:
  directories:
    - node_modules
notifications:
  email: false
script:
  - yarn run test
  - yarn global add travis-deploy-once semantic-release
  - travis-deploy-once "semantic-release"
