sudo: false
language: node_js
node_js:
  - 8
os:
  - linux
  - osx
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
script:
  - yarn test
  - yarn global add travis-deploy-once semantic-release
  - travis-deploy-once "semantic-release"
